sudo: required
services:
  - docker

before_install:
  - docker build -t znalbert/docker-react -f dev.dockerfile .

script:
  - docker run znalbert/docker-react npm run test:ci

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-306476627547'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
